mention SDKs runner on build failures
stripe/openapi pull request #162
Opened 2024-11-22 22:09 UTC by xavdid-stripe

In order to better surface build failures before our users notice them, it's useful for the runner to get pinged when a build fails (rather than hoping they look at the channel)

2024-11-23 00:14 UTC, xavdid-stripe commented
Looks like I can't turn auto-merge on, but feel free to merge this once it's approved! Or if it needs changes, I can tweak when I come back.

2024-12-05 17:34 UTC, jar-stripe requested changes

2024-12-05 17:34 UTC, jar-stripe commented on actions/notify-slack/action.yml
> +          <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|Commit> cc: <@S03C9B2JDDY>
can we externalize the channel id into a parameter or variable?

2024-12-06 01:00 UTC, xavdid-stripe commented on actions/notify-slack/action.yml
> +          <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|Commit> cc: <@S03C9B2JDDY>
We can, but then we'll have to set it in every repo that uses this action. Given that we're the only users of this workflow, IMO it makes the most sense to hardcode it here. If we need to parameterize it, we can.

2025-01-07 18:26 UTC, xavdid-stripe commented on actions/notify-slack/action.yml
> +          <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|Commit> cc: <@S03C9B2JDDY>
I've confirmed that slack IDs aren't sensitive values. https://github.com/slackapi/slack-github-action/issues/387

2025-01-07 18:27 UTC, jar-stripe approved these changes
LGTM!

2025-01-07 18:27 UTC, merged