Copy the beta openapi during updates
stripe/openapi pull request #84
Opened 2022-04-21 18:47 UTC by pakrym-stripe

To enable beta SDK generation we need to copy the beta SDK definition file as part of update process.

2022-04-21 19:10 UTC, richardm-stripe requested changes
Looks like CI needs an update.

2022-04-21 19:38 UTC, dcr-stripe commented on bin/update
> +        ["spec3.json", "spec3.yaml", "spec3.sdk.yaml", "spec3.sdk.json", "spec3.beta.sdk.yaml", "spec3.beta.sdk.json"],
We only produce a yaml file now for spec3.beta, so we shouldn't have the .json bit here.

2022-04-21 19:54 UTC, pakrym-stripe commented
Done, PTAL.

2022-04-22 17:27 UTC, richardm-stripe approved these changes

2022-04-22 17:29 UTC, merged